APP_SOURCEFILES = main.c
SOURCEDIRS = ../libs ../libs/aes128 ../libs/serial
CORE_SOURCEFILES = messaging.c util.c avr-asm-macros.S serial.c
CORE_SOURCEFILES += aes_dec.S aes_enc.S aes_invsbox.S aes_keyschedule.S aes_sbox.S gf256mul.S

include ../libs/SµV/Makefile.include
